name: Debug

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: python -m pip install --upgrade pip setuptools wheel build
    - name: Install Hatch
      uses: pypa/hatch@install
    - name: Debug
      run: |
        hatch new --init
        cat pyproject.toml
